"""Abaqus/CAE script builder for V3 rigid-frame bridge designs."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from bridge_fem_agent.rigid_frame.design import RigidFrameDesign, equivalent_box_properties, height_at_station
from bridge_fem_agent.rigid_frame.prestress import tendon_prestress_plan, write_prestress_verification
from bridge_fem_agent.rigid_frame.schema import RigidFrameInput

LOGGER = logging.getLogger(__name__)


class RigidFrameAbaqusBuilder:
    """Generate a reviewable Abaqus/CAE Python script for the optimized design."""

    def write(self, task: RigidFrameInput, design: RigidFrameDesign, workdir: Path) -> Path:
        workdir.mkdir(parents=True, exist_ok=True)
        write_prestress_verification(task, design, workdir)
        script_path = workdir / f"{task.project_name}_rigid_frame_build.py"
        script_path.write_text(self.render(task, design), encoding="utf-8")
        LOGGER.info("Wrote V3 rigid-frame Abaqus build script: %s", script_path)
        return script_path

    def render(self, task: RigidFrameInput, design: RigidFrameDesign) -> str:
        plan = self._build_plan(task, design)
        plan_json = json.dumps(plan, indent=2)
        return f'''# -*- coding: mbcs -*-
"""Generated by Text to Bridge V3 rigid-frame workflow.

Run with:
    abaqus cae noGUI={task.project_name}_rigid_frame_build.py

The script creates a reviewable three-span continuous rigid-frame bridge model.
The prestress tendons are represented as reviewable wire paths plus equivalent
balancing line loads for the fast global model.
"""

from __future__ import print_function

import json
import sys
from abaqus import *
from abaqusConstants import *
from caeModules import *
from driverUtils import executeOnCaeStartup
from mesh import ElemType
import regionToolset


PLAN = r"""{plan_json}"""


def abaqus_name(value):
    if sys.version_info[0] < 3:
        try:
            if isinstance(value, unicode):
                return value.encode("mbcs")
        except NameError:
            pass
    return str(value)


def value_or_unset(value):
    return UNSET if value is None else value


def make_edge_set(part, name, midpoint):
    edge = part.edges.findAt(((midpoint[0], midpoint[1], midpoint[2]),))
    part.Set(edges=edge, name=abaqus_name(name))
    return part.sets[abaqus_name(name)]


def build_model():
    executeOnCaeStartup()
    plan = json.loads(PLAN)
    project = abaqus_name(plan["project_name"])
    model_name = "RigidFrameV3"

    Mdb()
    try:
        del mdb.models["Model-1"]
    except Exception:
        pass
    model = mdb.Model(name=model_name)

    materials = plan["materials"]
    model.Material(name="GIRDER_CONCRETE")
    model.materials["GIRDER_CONCRETE"].Density(table=((materials["concrete_density_kg_m3"],),))
    model.materials["GIRDER_CONCRETE"].Elastic(table=((materials["girder_elastic_modulus_pa"], materials["concrete_poisson_ratio"]),))
    model.Material(name="PIER_CONCRETE")
    model.materials["PIER_CONCRETE"].Density(table=((materials["concrete_density_kg_m3"],),))
    model.materials["PIER_CONCRETE"].Elastic(table=((materials["pier_elastic_modulus_pa"], materials["concrete_poisson_ratio"]),))
    model.Material(name="PRESTRESS_STEEL")
    model.materials["PRESTRESS_STEEL"].Density(table=((7850.0,),))
    model.materials["PRESTRESS_STEEL"].Elastic(table=((materials["prestress_elastic_modulus_pa"], 0.3),))

    sketch = model.ConstrainedSketch(name="rigid_frame_axis", sheetSize=max(100.0, plan["total_length_m"] * 1.2))
    for seg in plan["girder_segments"]:
        sketch.Line(point1=(seg["x0"], 0.0), point2=(seg["x1"], 0.0))
    for pier in plan["piers"]:
        sketch.Line(point1=(pier["x"], 0.0), point2=(pier["x"], -pier["height"]))
    part = model.Part(name="RigidFrameBridge", dimensionality=THREE_D, type=DEFORMABLE_BODY)
    part.BaseWire(sketch=sketch)
    del model.sketches["rigid_frame_axis"]

    for index, seg in enumerate(plan["girder_segments"]):
        profile = "GirderProfile-%03d" % index
        section = "GirderSection-%03d" % index
        model.BoxProfile(name=profile, a=seg["width"], b=seg["height"], uniformThickness=OFF, t1=seg["top_slab_thickness"], t2=seg["web_thickness"], t3=seg["bottom_slab_thickness"], t4=seg["web_thickness"])
        model.BeamSection(name=section, integration=DURING_ANALYSIS, material="GIRDER_CONCRETE", profile=profile, poissonRatio=materials["concrete_poisson_ratio"])
        edge_set = make_edge_set(part, "GirderEdge-%03d" % index, ((seg["x0"] + seg["x1"]) / 2.0, 0.0, 0.0))
        part.SectionAssignment(region=edge_set, sectionName=section, offset=0.0, offsetType=MIDDLE_SURFACE, offsetField="", thicknessAssignment=FROM_SECTION)
        part.assignBeamSectionOrientation(region=edge_set, method=N1_COSINES, n1=(0.0, 0.0, -1.0))

    pier_profile = "PierProfile"
    model.RectangularProfile(name=pier_profile, a=plan["pier_section_width_m"], b=plan["pier_section_depth_m"])
    model.BeamSection(name="PierSection", integration=DURING_ANALYSIS, material="PIER_CONCRETE", profile=pier_profile, poissonRatio=materials["concrete_poisson_ratio"])
    for index, pier in enumerate(plan["piers"]):
        edge_set = make_edge_set(part, "PierEdge-%03d" % index, (pier["x"], -pier["height"] / 2.0, 0.0))
        part.SectionAssignment(region=edge_set, sectionName="PierSection", offset=0.0, offsetType=MIDDLE_SURFACE, offsetField="", thicknessAssignment=FROM_SECTION)
        part.assignBeamSectionOrientation(region=edge_set, method=N1_COSINES, n1=(1.0, 0.0, 0.0))

    part.setElementType(regions=(part.edges[:],), elemTypes=(ElemType(elemCode=B31, elemLibrary=STANDARD),))
    part.seedPart(size=plan["mesh_size_m"], deviationFactor=0.1, minSizeFactor=0.1)
    part.generateMesh()

    assembly = model.rootAssembly
    assembly.DatumCsysByDefault(CARTESIAN)
    instance = assembly.Instance(name="RigidFrameBridge-1", part=part, dependent=ON)
    assembly.Set(edges=instance.edges[:], name="RIGID_FRAME_ALL")

    def node_set_by_xy(name, x, y, tol):
        nodes = tuple(node for node in instance.nodes if abs(node.coordinates[0] - x) <= tol and abs(node.coordinates[1] - y) <= tol)
        if not nodes:
            nodes = tuple(node for node in instance.nodes if abs(node.coordinates[0] - x) <= tol)
        labels = tuple(node.label for node in nodes)
        assembly.Set(nodes=instance.nodes.sequenceFromLabels(labels), name=abaqus_name(name))

    tol = plan["mesh_size_m"] * 0.6
    node_set_by_xy("ABUTMENT_LEFT", 0.0, 0.0, tol)
    node_set_by_xy("ABUTMENT_RIGHT", plan["total_length_m"], 0.0, tol)
    for index, pier in enumerate(plan["piers"], start=1):
        node_set_by_xy("PIER%02d_BASE" % index, pier["x"], -pier["height"], tol)
        node_set_by_xy("PIER%02d_TOP" % index, pier["x"], 0.0, tol)

    for tendon in plan["tendon_groups"]:
        tendon_sketch = model.ConstrainedSketch(name=abaqus_name(tendon["name"] + "_sketch"), sheetSize=max(100.0, plan["total_length_m"] * 1.2))
        x0 = tendon["start_x_m"]
        x1 = tendon["end_x_m"]
        xm = 0.5 * (x0 + x1)
        z = tendon["eccentricity_m"]
        tendon_sketch.Spline(points=((x0, z), (xm, z * 1.15), (x1, z)))
        tendon_part = model.Part(name=abaqus_name(tendon["name"]), dimensionality=THREE_D, type=DEFORMABLE_BODY)
        tendon_part.BaseWire(sketch=tendon_sketch)
        del model.sketches[abaqus_name(tendon["name"] + "_sketch")]
        model.TrussSection(name=abaqus_name(tendon["name"] + "_Section"), material="PRESTRESS_STEEL", area=tendon["area_each_m2"] * tendon["count"])
        tendon_part.SectionAssignment(region=regionToolset.Region(edges=tendon_part.edges[:]), sectionName=abaqus_name(tendon["name"] + "_Section"))
        tendon_part.setElementType(regions=(tendon_part.edges[:],), elemTypes=(ElemType(elemCode=T3D2, elemLibrary=STANDARD),))
        tendon_part.seedPart(size=max(plan["mesh_size_m"] * 2.0, 2.0), deviationFactor=0.1, minSizeFactor=0.1)
        tendon_part.generateMesh()
        tendon_instance = assembly.Instance(name=abaqus_name(tendon["name"] + "-1"), part=tendon_part, dependent=ON)
        assembly.Set(nodes=tendon_instance.nodes[:], name=abaqus_name(tendon["name"] + "_PATH_NODES"))

    if plan["analysis_type"] == "frequency":
        model.FrequencyStep(name="FrequencyStep", previous="Initial", numEigen=10)
        active_step = "FrequencyStep"
    else:
        model.StaticStep(name="ServiceLoad", previous="Initial", initialInc=0.1, maxInc=0.2, nlgeom=OFF)
        active_step = "ServiceLoad"

    model.DisplacementBC(name="BC_ABUTMENT_LEFT", createStepName="Initial", region=assembly.sets["ABUTMENT_LEFT"], u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=UNSET, ur3=UNSET)
    model.DisplacementBC(name="BC_ABUTMENT_RIGHT", createStepName="Initial", region=assembly.sets["ABUTMENT_RIGHT"], u1=UNSET, u2=0.0, u3=0.0, ur1=UNSET, ur2=UNSET, ur3=UNSET)
    for index, pier in enumerate(plan["piers"], start=1):
        model.DisplacementBC(name="BC_PIER%02d_BASE" % index, createStepName="Initial", region=assembly.sets["PIER%02d_BASE" % index], u1=0.0, u2=0.0, u3=0.0, ur1=0.0, ur2=0.0, ur3=0.0)
    for tendon in plan["tendon_groups"]:
        model.DisplacementBC(name=abaqus_name("BC_" + tendon["name"] + "_PATH"), createStepName="Initial", region=assembly.sets[abaqus_name(tendon["name"] + "_PATH_NODES")], u1=0.0, u2=0.0, u3=0.0, ur1=UNSET, ur2=UNSET, ur3=UNSET)

    model.Gravity(name="Load-G", createStepName=active_step, comp2=-9.81, distributionType=UNIFORM, field="")
    girder_region = regionToolset.Region(edges=instance.edges[:])
    model.LineLoad(name="Load-road", createStepName=active_step, region=girder_region, comp2=-plan["road_line_load_n_m"], distributionType=UNIFORM, field="")
    if plan["prestress_mode"] == "equivalent_load":
        model.LineLoad(name="Load-prestress-equivalent", createStepName=active_step, region=girder_region, comp2=plan["prestress_balancing_load_n_m"], distributionType=UNIFORM, field="")

    model.FieldOutputRequest(name="F-Output-RigidFrame", createStepName=active_step, variables=("S", "U", "RF"))
    model.HistoryOutputRequest(name="H-Output-PierBase", createStepName=active_step, variables=("RF1", "RF2", "RF3"), region=assembly.sets["PIER01_BASE"])

    job = mdb.Job(name=project, model=model_name, description="Generated V3 rigid-frame bridge", type=ANALYSIS, memory=90, memoryUnits=PERCENTAGE, echoPrint=OFF, modelPrint=OFF, contactPrint=OFF, historyPrint=OFF)
    job.writeInput(consistencyChecking=OFF)
    mdb.saveAs(pathName=project + ".cae")
    print("Generated V3 rigid-frame model: " + project + ".cae and " + project + ".inp")


if __name__ == "__main__":
    build_model()
'''

    def _build_plan(self, task: RigidFrameInput, design: RigidFrameDesign) -> dict[str, Any]:
        stations = self._stations(task)
        segments = []
        for x0, x1 in zip(stations[:-1], stations[1:]):
            xm = 0.5 * (x0 + x1)
            height = height_at_station(task, design.section, xm)
            area, inertia = equivalent_box_properties(design.section, height)
            segments.append(
                {
                    "x0": x0,
                    "x1": x1,
                    "height": height,
                    "width": design.section.deck_width_m,
                    "area": area,
                    "inertia": inertia,
                    "torsion": inertia * 0.25,
                    "web_thickness": design.section.web_thickness_m,
                    "bottom_slab_thickness": design.section.bottom_slab_thickness_m,
                    "top_slab_thickness": design.section.top_slab_thickness_m,
                }
            )
        avg_height = 0.55 * design.section.pier_height_m + 0.45 * design.section.midspan_height_m
        area, _ = equivalent_box_properties(design.section, avg_height)
        road_line_load = (task.roadway_load_pa + task.human_load_pa + task.second_dead_load_pa) * task.deck_width_m
        prestress_force = sum(group.total_force_n for group in design.tendon_groups)
        prestress_balancing = min(0.45 * road_line_load, prestress_force / max(task.total_length_m, 1.0) * 0.015)
        return {
            "project_name": task.project_name,
            "analysis_type": "static",
            "spans_m": task.spans_m,
            "total_length_m": task.total_length_m,
            "girder_segments": segments,
            "piers": [{"name": "pier01", "x": task.pier_stations_m[0], "height": task.resolved_pier_height_m}, {"name": "pier02", "x": task.pier_stations_m[1], "height": task.resolved_pier_height_m}],
            "pier_section_width_m": max(2.5, task.deck_width_m * 0.25),
            "pier_section_depth_m": max(2.5, task.deck_width_m * 0.22),
            "mesh_size_m": max(min(task.main_span_m / 40.0, 4.0), 1.0),
            "materials": task.materials.__dict__,
            "prestress_mode": task.prestress_mode,
            "tendon_groups": [tendon_prestress_plan(group, task) for group in design.tendon_groups],
            "road_line_load_n_m": road_line_load,
            "prestress_balancing_load_n_m": prestress_balancing,
            "estimated_area_m2": area,
            "response": design.response.__dict__ if design.response else None,
        }

    def _stations(self, task: RigidFrameInput) -> list[float]:
        stations = {0.0, task.total_length_m, *task.pier_stations_m}
        span_start = 0.0
        for span in task.spans_m:
            for index in range(1, 8):
                stations.add(round(span_start + span * index / 8.0, 6))
            span_start += span
        return sorted(stations)
