"""Abaqus/CAE solid-element builder for V5 construction-detail rigid frames."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from bridge_fem_agent.rigid_frame.design import RigidFrameDesign, height_at_station
from bridge_fem_agent.rigid_frame.schema import RigidFrameInput

LOGGER = logging.getLogger(__name__)


class ConstructionSolidRigidFrameBuilder:
    """Generate a C3D8R box girder with hollow spans and solid diaphragm zones."""

    def write(self, task: RigidFrameInput, design: RigidFrameDesign, workdir: Path) -> Path:
        workdir.mkdir(parents=True, exist_ok=True)
        script_path = workdir / f"{task.project_name}_rigid_frame_construction_solid_build.py"
        script_path.write_text(self.render(task, design), encoding="utf-8")
        LOGGER.info("Wrote V5 construction-solid rigid-frame Abaqus build script: %s", script_path)
        return script_path

    def render(self, task: RigidFrameInput, design: RigidFrameDesign) -> str:
        plan = self._build_plan(task, design)
        plan_json = json.dumps(plan, indent=2)
        return f'''# -*- coding: mbcs -*-
"""Generated by Text to Bridge V5 construction-solid rigid-frame workflow."""

from __future__ import print_function

import json
import math
import sys
from abaqus import *
from abaqusConstants import *
from caeModules import *
from driverUtils import executeOnCaeStartup
from mesh import ElemType
import regionToolset


PLAN = r"""{plan_json}"""
PLAN_DATA = json.loads(PLAN)
MESH_CONTROLS = PLAN_DATA.get("mesh_controls", {{}})


def abaqus_name(value):
    if sys.version_info[0] < 3:
        try:
            if isinstance(value, unicode):
                return value.encode("mbcs")
        except NameError:
            pass
    return str(value)


def rounded_key(coord):
    return tuple(round(float(item), 6) for item in coord)


def get_node(node_map, nodes, coord):
    key = rounded_key(coord)
    if key not in node_map:
        node_map[key] = len(nodes) + 1
        nodes.append(key)
    return node_map[key]


def add_hex(node_map, nodes, elements, labels, coords):
    element_nodes = tuple(get_node(node_map, nodes, coord) for coord in coords)
    elements.append(element_nodes)
    label = len(elements)
    labels.append(label)
    return label


def axis_points(start, end, max_size, min_divisions=1):
    length = abs(end - start)
    divisions = max(int(min_divisions), int(math.ceil(length / max(max_size, 1.0e-9))))
    return [start + (end - start) * float(index) / float(divisions) for index in range(divisions + 1)]


def ratio_points(divisions):
    return [float(index) / float(divisions) for index in range(divisions + 1)]


def lerp(left, right, ratio):
    return left + (right - left) * ratio


def y_at(y0_left, y1_left, y0_right, y1_right, x_ratio, y_ratio):
    lower = lerp(y0_left, y0_right, x_ratio)
    upper = lerp(y1_left, y1_right, x_ratio)
    return lerp(lower, upper, y_ratio)


def add_box_variable_y(node_map, nodes, elements, labels, x0, x1, y0_left, y1_left, y0_right, y1_right, z0, z1):
    if x1 <= x0 or y1_left <= y0_left or y1_right <= y0_right or z1 <= z0:
        return []
    max_dx = MESH_CONTROLS.get("longitudinal_size_m", 2.0)
    max_dy = MESH_CONTROLS.get("vertical_size_m", 0.75)
    max_dz = MESH_CONTROLS.get("transverse_size_m", 0.90)
    x_points = axis_points(x0, x1, max_dx)
    z_points = axis_points(z0, z1, max_dz)
    average_y_size = 0.5 * ((y1_left - y0_left) + (y1_right - y0_right))
    y_divisions = max(1, int(math.ceil(average_y_size / max(max_dy, 1.0e-9))))
    y_ratios = ratio_points(y_divisions)
    created = []
    for ix in range(len(x_points) - 1):
        xa = x_points[ix]
        xb = x_points[ix + 1]
        ra = (xa - x0) / max(x1 - x0, 1.0e-9)
        rb = (xb - x0) / max(x1 - x0, 1.0e-9)
        for iy in range(len(y_ratios) - 1):
            ya0 = y_at(y0_left, y1_left, y0_right, y1_right, ra, y_ratios[iy])
            ya1 = y_at(y0_left, y1_left, y0_right, y1_right, ra, y_ratios[iy + 1])
            yb0 = y_at(y0_left, y1_left, y0_right, y1_right, rb, y_ratios[iy])
            yb1 = y_at(y0_left, y1_left, y0_right, y1_right, rb, y_ratios[iy + 1])
            for iz in range(len(z_points) - 1):
                za = z_points[iz]
                zb = z_points[iz + 1]
                created.append(
                    add_hex(
                        node_map,
                        nodes,
                        elements,
                        labels,
                        (
                            (xa, ya0, za),
                            (xb, yb0, za),
                            (xb, yb1, za),
                            (xa, ya1, za),
                            (xa, ya0, zb),
                            (xb, yb0, zb),
                            (xb, yb1, zb),
                            (xa, ya1, zb),
                        ),
                    )
                )
    return created


def add_box(node_map, nodes, elements, labels, x0, x1, y0, y1, z0, z1):
    return add_box_variable_y(node_map, nodes, elements, labels, x0, x1, y0, y1, y0, y1, z0, z1)


def station_props(plan, x):
    stations = plan["stations"]
    if x <= stations[0]["x"]:
        return stations[0]
    if x >= stations[-1]["x"]:
        return stations[-1]
    for left, right in zip(stations[:-1], stations[1:]):
        if left["x"] <= x <= right["x"]:
            span = max(right["x"] - left["x"], 1.0e-9)
            ratio = (x - left["x"]) / span
            result = {{}}
            for key in left.keys():
                if key == "x":
                    result[key] = x
                elif isinstance(left[key], (int, float)):
                    result[key] = left[key] + (right[key] - left[key]) * ratio
                else:
                    result[key] = left[key]
            return result
    return stations[-1]


def section_z_points(props):
    width = props["deck_width_m"]
    bottom_width = props["bottom_box_width_m"]
    web_t = props["web_thickness_m"]
    left_inner = (width - bottom_width) / 2.0
    right_inner = (width + bottom_width) / 2.0
    left_outer = max(0.0, left_inner - web_t)
    right_outer = min(width, right_inner + web_t)
    points = [0.0, left_outer, left_inner, right_inner, right_outer, width]
    return sorted(set(round(point, 6) for point in points))


def build_concrete_mesh(plan):
    node_map = {{}}
    nodes = []
    girder_elements = []
    pier_elements = []
    girder_labels = []
    pier_labels = []
    solid_diaphragm_labels = []

    for left, right in zip(plan["stations"][:-1], plan["stations"][1:]):
        x0 = left["x"]
        x1 = right["x"]
        left_props = station_props(plan, x0)
        right_props = station_props(plan, x1)
        pm = station_props(plan, 0.5 * (x0 + x1))
        height_l = left_props["height_m"]
        height_r = right_props["height_m"]
        top_t_l = left_props["top_slab_thickness_m"]
        top_t_r = right_props["top_slab_thickness_m"]
        bottom_t_l = left_props["bottom_slab_thickness_m"]
        bottom_t_r = right_props["bottom_slab_thickness_m"]
        width = pm["deck_width_m"]
        bottom_width = pm["bottom_box_width_m"]
        left_inner = (width - bottom_width) / 2.0
        right_inner = (width + bottom_width) / 2.0
        left_outer = max(0.0, left_inner - pm["web_thickness_m"])
        right_outer = min(width, right_inner + pm["web_thickness_m"])
        z_points = section_z_points(pm)

        for z0, z1 in zip(z_points[:-1], z_points[1:]):
            add_box_variable_y(node_map, nodes, girder_elements, girder_labels, x0, x1, -top_t_l, 0.0, -top_t_r, 0.0, z0, z1)
        for z0, z1 in ((left_outer, left_inner), (right_inner, right_outer)):
            add_box_variable_y(node_map, nodes, girder_elements, girder_labels, x0, x1, -height_l + bottom_t_l, -top_t_l, -height_r + bottom_t_r, -top_t_r, z0, z1)
        for z0, z1 in ((left_outer, left_inner), (left_inner, right_inner), (right_inner, right_outer)):
            add_box_variable_y(node_map, nodes, girder_elements, girder_labels, x0, x1, -height_l, -height_l + bottom_t_l, -height_r, -height_r + bottom_t_r, z0, z1)

        if pm["solid_zone"] != "hollow":
            added = add_box_variable_y(
                node_map,
                nodes,
                girder_elements,
                girder_labels,
                x0,
                x1,
                -height_l + bottom_t_l,
                -top_t_l,
                -height_r + bottom_t_r,
                -top_t_r,
                left_inner,
                right_inner,
            )
            solid_diaphragm_labels.extend(added)

    for pier in plan["piers"]:
        z0 = pier["z_min"]
        z1 = pier["z_max"]
        x0 = pier["x"] - pier["width_m"] / 2.0
        x1 = pier["x"] + pier["width_m"] / 2.0
        left_props = station_props(plan, x0)
        right_props = station_props(plan, x1)
        y_top_left = -left_props["height_m"]
        y_top_right = -right_props["height_m"]
        pier_slices = max(3, int(pier["height_m"] / plan["mesh_size_m"]))
        for index in range(pier_slices):
            upper_ratio = float(index) / float(pier_slices)
            lower_ratio = float(index + 1) / float(pier_slices)
            y_upper_left = y_top_left + (-pier["height_m"] - y_top_left) * upper_ratio
            y_lower_left = y_top_left + (-pier["height_m"] - y_top_left) * lower_ratio
            y_upper_right = y_top_right + (-pier["height_m"] - y_top_right) * upper_ratio
            y_lower_right = y_top_right + (-pier["height_m"] - y_top_right) * lower_ratio
            add_box_variable_y(node_map, nodes, pier_elements, pier_labels, x0, x1, y_lower_left, y_upper_left, y_lower_right, y_upper_right, z0, z1)

    return nodes, girder_elements, pier_elements, girder_labels, pier_labels, solid_diaphragm_labels


def build_tendon_mesh(plan, tendon):
    nodes = []
    elements = []
    count = max(4, int(abs(tendon["end_x_m"] - tendon["start_x_m"]) / max(plan["mesh_size_m"] * 1.5, 1.0)))
    for index in range(count + 1):
        ratio = float(index) / float(count)
        x = tendon["start_x_m"] + (tendon["end_x_m"] - tendon["start_x_m"]) * ratio
        props = station_props(plan, x)
        if tendon["role"] == "pier_top_negative_moment":
            y = -0.50 * props["top_slab_thickness_m"]
        else:
            y = -props["height_m"] + 0.50 * props["bottom_slab_thickness_m"]
        z = plan["deck_width_m"] / 2.0
        nodes.append((x, y, z))
    for index in range(count):
        elements.append((index + 1, index + 2))
    return nodes, elements


def build_model():
    executeOnCaeStartup()
    plan = json.loads(PLAN)
    project = abaqus_name(plan["project_name"])
    model_name = "RigidFrameV5ConstructionSolid"

    Mdb()
    try:
        del mdb.models["Model-1"]
    except Exception:
        pass
    model = mdb.Model(name=model_name)

    materials = plan["materials"]
    model.Material(name="GIRDER_CONCRETE")
    model.materials["GIRDER_CONCRETE"].Density(table=((materials["concrete_density_kg_m3"],),))
    model.materials["GIRDER_CONCRETE"].Elastic(table=((materials["girder_elastic_modulus_pa"], materials["concrete_poisson_ratio"]),))
    model.Material(name="PIER_CONCRETE")
    model.materials["PIER_CONCRETE"].Density(table=((materials["concrete_density_kg_m3"],),))
    model.materials["PIER_CONCRETE"].Elastic(table=((materials["pier_elastic_modulus_pa"], materials["concrete_poisson_ratio"]),))
    model.Material(name="PRESTRESS_STEEL")
    model.materials["PRESTRESS_STEEL"].Density(table=((7850.0,),))
    model.materials["PRESTRESS_STEEL"].Elastic(table=((materials["prestress_elastic_modulus_pa"], 0.3),))

    concrete_part = model.Part(name="ConstructionSolidRigidFrame", dimensionality=THREE_D, type=DEFORMABLE_BODY)
    nodes, girder_elements, pier_elements, girder_labels, pier_labels, solid_diaphragm_labels = build_concrete_mesh(plan)
    for label, coord in enumerate(nodes, start=1):
        concrete_part.Node(coordinates=coord, label=label)
    for label, connectivity in enumerate(girder_elements + pier_elements, start=1):
        concrete_part.Element(nodes=tuple(concrete_part.nodes.sequenceFromLabels(tuple(connectivity))), elemShape=HEX8, label=label)
    concrete_part.Set(elements=concrete_part.elements.sequenceFromLabels(tuple(girder_labels)), name="GIRDER_CONCRETE_ELEMENTS")
    if solid_diaphragm_labels:
        concrete_part.Set(elements=concrete_part.elements.sequenceFromLabels(tuple(solid_diaphragm_labels)), name="SOLID_DIAPHRAGM_ELEMENTS")
    pier_offset = len(girder_elements)
    concrete_part.Set(elements=concrete_part.elements.sequenceFromLabels(tuple(label + pier_offset for label in pier_labels)), name="PIER_CONCRETE_ELEMENTS")
    model.HomogeneousSolidSection(name="GirderConcreteSection", material="GIRDER_CONCRETE", thickness=None)
    model.HomogeneousSolidSection(name="PierConcreteSection", material="PIER_CONCRETE", thickness=None)
    concrete_part.SectionAssignment(region=concrete_part.sets["GIRDER_CONCRETE_ELEMENTS"], sectionName="GirderConcreteSection")
    concrete_part.SectionAssignment(region=concrete_part.sets["PIER_CONCRETE_ELEMENTS"], sectionName="PierConcreteSection")
    concrete_part.setElementType(regions=(concrete_part.elements[:],), elemTypes=(ElemType(elemCode=C3D8R, elemLibrary=STANDARD),))

    assembly = model.rootAssembly
    assembly.DatumCsysByDefault(CARTESIAN)
    concrete_instance = assembly.Instance(name="ConstructionSolidRigidFrame-1", part=concrete_part, dependent=ON)
    assembly.Set(elements=concrete_instance.elements[:], name="CONCRETE_HOST")

    tol = plan["mesh_size_m"] * 0.35
    top_nodes = tuple(node for node in concrete_instance.nodes if abs(node.coordinates[1]) <= 1.0e-6)
    assembly.Set(nodes=concrete_instance.nodes.sequenceFromLabels(tuple(node.label for node in top_nodes)), name="DECK_TOP_NODES")

    def node_set_by_box(name, x_min, x_max, y_min, y_max):
        selected = tuple(
            node for node in concrete_instance.nodes
            if x_min - tol <= node.coordinates[0] <= x_max + tol
            and y_min - tol <= node.coordinates[1] <= y_max + tol
        )
        assembly.Set(nodes=concrete_instance.nodes.sequenceFromLabels(tuple(node.label for node in selected)), name=abaqus_name(name))

    node_set_by_box("ABUTMENT_LEFT", 0.0, 0.0, -plan["end_depth_m"], 0.0)
    node_set_by_box("ABUTMENT_RIGHT", plan["total_length_m"], plan["total_length_m"], -plan["end_depth_m"], 0.0)
    for index, pier in enumerate(plan["piers"], start=1):
        node_set_by_box("PIER%02d_BASE" % index, pier["x"] - pier["width_m"] / 2.0, pier["x"] + pier["width_m"] / 2.0, -pier["height_m"], -pier["height_m"])

    for tendon in plan["tendon_groups"]:
        tendon_part = model.Part(name=abaqus_name(tendon["name"]), dimensionality=THREE_D, type=DEFORMABLE_BODY)
        tendon_nodes, tendon_elements = build_tendon_mesh(plan, tendon)
        for label, coord in enumerate(tendon_nodes, start=1):
            tendon_part.Node(coordinates=coord, label=label)
        for label, connectivity in enumerate(tendon_elements, start=1):
            tendon_part.Element(nodes=tuple(tendon_part.nodes.sequenceFromLabels(tuple(connectivity))), elemShape=LINE2, label=label)
        model.TrussSection(name=abaqus_name(tendon["name"] + "_Section"), material="PRESTRESS_STEEL", area=tendon["area_each_m2"] * tendon["count"])
        tendon_part.Set(elements=tendon_part.elements[:], name="TENDON_ELEMENTS")
        tendon_part.SectionAssignment(region=tendon_part.sets["TENDON_ELEMENTS"], sectionName=abaqus_name(tendon["name"] + "_Section"))
        tendon_part.setElementType(regions=(tendon_part.elements[:],), elemTypes=(ElemType(elemCode=T3D2, elemLibrary=STANDARD),))
        tendon_instance = assembly.Instance(name=abaqus_name(tendon["name"] + "-1"), part=tendon_part, dependent=ON)
        assembly.Set(elements=tendon_instance.elements[:], name=abaqus_name(tendon["name"] + "_EMBEDDED_ELEMENTS"))
        model.EmbeddedRegion(
            name=abaqus_name("Embed_" + tendon["name"]),
            embeddedRegion=regionToolset.Region(elements=tendon_instance.elements[:]),
            hostRegion=regionToolset.Region(elements=concrete_instance.elements[:]),
            weightFactorTolerance=1.0e-6,
            absoluteTolerance=0.0,
            fractionalTolerance=0.05,
            toleranceMethod=BOTH,
        )

    model.StaticStep(name="ServiceLoad", previous="Initial", initialInc=0.1, maxInc=0.2, nlgeom=OFF)
    model.DisplacementBC(name="BC_ABUTMENT_LEFT", createStepName="Initial", region=assembly.sets["ABUTMENT_LEFT"], u1=0.0, u2=0.0, u3=0.0)
    model.DisplacementBC(name="BC_ABUTMENT_RIGHT", createStepName="Initial", region=assembly.sets["ABUTMENT_RIGHT"], u1=UNSET, u2=0.0, u3=0.0)
    for index in range(1, 3):
        model.DisplacementBC(name="BC_PIER%02d_BASE" % index, createStepName="Initial", region=assembly.sets["PIER%02d_BASE" % index], u1=0.0, u2=0.0, u3=0.0)

    model.Gravity(name="Load-G", createStepName="ServiceLoad", comp2=-9.81, distributionType=UNIFORM, field="")
    road_force = -plan["road_line_load_n_m"] * plan["total_length_m"] / max(len(top_nodes), 1)
    prestress_force = plan["prestress_balancing_load_n_m"] * plan["total_length_m"] / max(len(top_nodes), 1)
    model.ConcentratedForce(name="Load-road-equivalent", createStepName="ServiceLoad", region=assembly.sets["DECK_TOP_NODES"], cf2=road_force)
    model.ConcentratedForce(name="Load-prestress-equivalent", createStepName="ServiceLoad", region=assembly.sets["DECK_TOP_NODES"], cf2=prestress_force)

    model.FieldOutputRequest(name="F-Output-ConstructionSolid", createStepName="ServiceLoad", variables=("S", "U", "RF"))
    model.HistoryOutputRequest(name="H-Output-PierBase", createStepName="ServiceLoad", variables=("RF1", "RF2", "RF3"), region=assembly.sets["PIER01_BASE"])
    job = mdb.Job(name=project, model=model_name, description="Generated V5 construction-solid rigid-frame bridge", type=ANALYSIS, memory=90, memoryUnits=PERCENTAGE, echoPrint=OFF, modelPrint=OFF, contactPrint=OFF, historyPrint=OFF)
    job.writeInput(consistencyChecking=OFF)
    mdb.saveAs(pathName=project + ".cae")
    print("Generated V5 construction-solid rigid-frame model: " + project + ".cae and " + project + ".inp")


if __name__ == "__main__":
    build_model()
'''

    def _build_plan(self, task: RigidFrameInput, design: RigidFrameDesign) -> dict[str, Any]:
        stations = self._stations(task, design)
        pier_width = max(4.0, task.deck_width_m * 0.32)
        pier_z = self._pier_z(task, design)
        end_solid_length = self._end_solid_length(task)
        pier_solid_half_length = self._pier_solid_half_length(task, pier_width)
        road_line_load = (task.roadway_load_pa + task.human_load_pa + task.second_dead_load_pa) * task.deck_width_m
        prestress_force = sum(group.total_force_n for group in design.tendon_groups)
        prestress_balancing = min(0.45 * road_line_load, prestress_force / max(task.total_length_m, 1.0) * 0.015)
        return {
            "project_name": task.project_name,
            "spans_m": task.spans_m,
            "total_length_m": task.total_length_m,
            "deck_width_m": task.deck_width_m,
            "end_depth_m": height_at_station(task, design.section, 0.0),
            "mesh_size_m": max(min(task.main_span_m / 60.0, 3.5), 1.5),
            "mesh_controls": {
                "longitudinal_size_m": max(min(task.main_span_m / 90.0, 2.2), 1.2),
                "vertical_size_m": max(min(task.main_span_m / 180.0, 0.85), 0.45),
                "transverse_size_m": max(min(task.deck_width_m / 14.0, 0.95), 0.55),
            },
            "end_solid_length_m": end_solid_length,
            "pier_solid_half_length_m": pier_solid_half_length,
            "stations": [self._station_plan(task, design, x) for x in stations],
            "materials": task.materials.__dict__,
            "piers": [
                {"name": "pier01", "x": task.pier_stations_m[0], "height_m": task.resolved_pier_height_m, "width_m": pier_width, **pier_z},
                {"name": "pier02", "x": task.pier_stations_m[1], "height_m": task.resolved_pier_height_m, "width_m": pier_width, **pier_z},
            ],
            "tendon_groups": [group.__dict__ for group in design.tendon_groups],
            "road_line_load_n_m": road_line_load,
            "prestress_balancing_load_n_m": prestress_balancing,
            "response": design.response.__dict__ if design.response else None,
        }

    def _station_plan(self, task: RigidFrameInput, design: RigidFrameDesign, x_m: float) -> dict[str, Any]:
        height = height_at_station(task, design.section, x_m)
        bottom_box_width = max(task.deck_width_m * 0.48, 3.5)
        solid_zone = self._solid_zone(task, x_m)
        return {
            "x": x_m,
            "height_m": height,
            "deck_width_m": task.deck_width_m,
            "bottom_box_width_m": bottom_box_width,
            "web_thickness_m": min(design.section.web_thickness_m, bottom_box_width * 0.22),
            "top_slab_thickness_m": min(design.section.top_slab_thickness_m, height * 0.22),
            "bottom_slab_thickness_m": self._bottom_slab_thickness(task, design, x_m, height, solid_zone),
            "solid_zone": solid_zone,
        }

    def _pier_z(self, task: RigidFrameInput, design: RigidFrameDesign) -> dict[str, float]:
        bottom_box_width = max(task.deck_width_m * 0.48, 3.5)
        z_min = (task.deck_width_m - bottom_box_width) / 2.0
        z_max = (task.deck_width_m + bottom_box_width) / 2.0
        return {"z_min": z_min, "z_max": z_max}

    def _stations(self, task: RigidFrameInput, design: RigidFrameDesign) -> list[float]:
        stations = {0.0, task.total_length_m, *task.pier_stations_m}
        span_start = 0.0
        for span in task.spans_m:
            divisions = max(5, int(span / max(task.main_span_m / 8.0, 1.0)))
            for index in range(1, divisions):
                stations.add(round(span_start + span * index / divisions, 6))
            span_start += span
        pier_width = max(4.0, task.deck_width_m * 0.32)
        end_solid = self._end_solid_length(task)
        stations.add(round(end_solid, 6))
        stations.add(round(task.total_length_m - end_solid, 6))
        bottom_taper = self._bottom_thickness_transition_length(task)
        for ratio in (1.0 / 3.0, 2.0 / 3.0, 1.0):
            stations.add(round(min(task.total_length_m, end_solid + bottom_taper * ratio), 6))
            stations.add(round(max(0.0, task.total_length_m - end_solid - bottom_taper * ratio), 6))
        pier_solid_half = self._pier_solid_half_length(task, pier_width)
        for pier in task.pier_stations_m:
            stations.add(round(max(0.0, pier - pier_width / 2.0), 6))
            stations.add(round(min(task.total_length_m, pier + pier_width / 2.0), 6))
            stations.add(round(max(0.0, pier - pier_solid_half), 6))
            stations.add(round(min(task.total_length_m, pier + pier_solid_half), 6))
            for ratio in (1.0 / 3.0, 2.0 / 3.0, 1.0):
                stations.add(round(max(0.0, pier - pier_solid_half - bottom_taper * ratio), 6))
                stations.add(round(min(task.total_length_m, pier + pier_solid_half + bottom_taper * ratio), 6))
        return sorted(station for station in stations if 0.0 <= station <= task.total_length_m)

    def _end_solid_length(self, task: RigidFrameInput) -> float:
        return max(3.5, min(task.side_span_left_m, task.side_span_right_m) * 0.045)

    def _pier_solid_half_length(self, task: RigidFrameInput, pier_width: float) -> float:
        return max(pier_width * 0.65, task.main_span_m * 0.020)

    def _bottom_thickness_transition_length(self, task: RigidFrameInput) -> float:
        return max(10.0, task.main_span_m * 0.16)

    def _solid_zone(self, task: RigidFrameInput, x_m: float) -> str:
        end_solid = self._end_solid_length(task)
        pier_width = max(4.0, task.deck_width_m * 0.32)
        pier_half = self._pier_solid_half_length(task, pier_width)
        if x_m <= end_solid:
            return "left_end_solid"
        if x_m >= task.total_length_m - end_solid:
            return "right_end_solid"
        for index, pier_x in enumerate(task.pier_stations_m, start=1):
            if abs(x_m - pier_x) <= pier_half:
                return f"pier{index:02d}_solid"
        return "hollow"

    def _bottom_slab_thickness(self, task: RigidFrameInput, design: RigidFrameDesign, x_m: float, height: float, solid_zone: str) -> float:
        base = min(design.section.bottom_slab_thickness_m, height * 0.18)
        transition = self._bottom_thickness_transition_length(task)
        pier_width = max(4.0, task.deck_width_m * 0.32)
        pier_half = self._pier_solid_half_length(task, pier_width)
        nearest_pier_distance = min(abs(x_m - pier) for pier in task.pier_stations_m)
        pier_ratio = self._smooth_ratio(max(nearest_pier_distance - pier_half, 0.0), transition)
        end_distance = min(x_m, task.total_length_m - x_m)
        end_ratio = self._smooth_ratio(max(end_distance - self._end_solid_length(task), 0.0), transition)
        thickened = base * (1.0 + 1.20 * pier_ratio + 0.42 * end_ratio)
        return min(thickened, height * 0.36)

    def _smooth_ratio(self, distance_m: float, transition_m: float) -> float:
        ratio = max(0.0, min(distance_m / max(transition_m, 1.0e-9), 1.0))
        smooth = ratio * ratio * (3.0 - 2.0 * ratio)
        return 1.0 - smooth
