"""Abaqus/CAE solid script builder for V3 continuous rigid-frame bridges."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from bridge_fem_agent.rigid_frame.design import RigidFrameDesign, height_at_station
from bridge_fem_agent.rigid_frame.schema import RigidFrameInput

LOGGER = logging.getLogger(__name__)


class RigidFrameSolidAbaqusBuilder:
    """Generate a monolithic solid rigid-frame bridge model for Abaqus/CAE."""

    def write(self, task: RigidFrameInput, design: RigidFrameDesign, workdir: Path) -> Path:
        workdir.mkdir(parents=True, exist_ok=True)
        script_path = workdir / f"{task.project_name}_rigid_frame_solid_build.py"
        script_path.write_text(self.render(task, design), encoding="utf-8")
        LOGGER.info("Wrote V3 rigid-frame solid Abaqus build script: %s", script_path)
        return script_path

    def render(self, task: RigidFrameInput, design: RigidFrameDesign) -> str:
        plan = self._build_plan(task, design)
        plan_json = json.dumps(plan, indent=2)
        return f'''# -*- coding: mbcs -*-
"""Generated by Text to Bridge V3 rigid-frame solid workflow.

Run with:
    abaqus cae noGUI={task.project_name}_rigid_frame_solid_build.py

The model uses a monolithic solid extrusion for the main girder and piers.
Prestress tendons are embedded truss paths inside the concrete host. Their
global prestress action is represented by an equivalent upward service
balancing load in this V3 model.
"""

from __future__ import print_function

import json
import sys
from abaqus import *
from abaqusConstants import *
from caeModules import *
from driverUtils import executeOnCaeStartup
from mesh import ElemType
import regionToolset


PLAN = r"""{plan_json}"""


def abaqus_name(value):
    if sys.version_info[0] < 3:
        try:
            if isinstance(value, unicode):
                return value.encode("mbcs")
        except NameError:
            pass
    return str(value)


def build_model():
    executeOnCaeStartup()
    plan = json.loads(PLAN)
    project = abaqus_name(plan["project_name"])
    model_name = "RigidFrameV3Solid"

    Mdb()
    try:
        del mdb.models["Model-1"]
    except Exception:
        pass
    model = mdb.Model(name=model_name)

    materials = plan["materials"]
    model.Material(name="GIRDER_CONCRETE")
    model.materials["GIRDER_CONCRETE"].Density(table=((materials["concrete_density_kg_m3"],),))
    model.materials["GIRDER_CONCRETE"].Elastic(table=((materials["girder_elastic_modulus_pa"], materials["concrete_poisson_ratio"]),))
    model.Material(name="PIER_CONCRETE")
    model.materials["PIER_CONCRETE"].Density(table=((materials["concrete_density_kg_m3"],),))
    model.materials["PIER_CONCRETE"].Elastic(table=((materials["pier_elastic_modulus_pa"], materials["concrete_poisson_ratio"]),))
    model.Material(name="PRESTRESS_STEEL")
    model.materials["PRESTRESS_STEEL"].Density(table=((7850.0,),))
    model.materials["PRESTRESS_STEEL"].Elastic(table=((materials["prestress_elastic_modulus_pa"], 0.3),))

    sketch = model.ConstrainedSketch(name="rigid_frame_solid_profile", sheetSize=max(100.0, plan["total_length_m"] * 1.25))
    outline = plan["outline_xy"]
    for start, end in zip(outline[:-1], outline[1:]):
        sketch.Line(point1=(start[0], start[1]), point2=(end[0], end[1]))
    part = model.Part(name="RigidFrameSolid", dimensionality=THREE_D, type=DEFORMABLE_BODY)
    part.BaseSolidExtrude(depth=plan["deck_width_m"], sketch=sketch)
    del model.sketches["rigid_frame_solid_profile"]

    for x in plan["partition_stations_m"]:
        try:
            datum = part.DatumPlaneByPrincipalPlane(principalPlane=YZPLANE, offset=x)
            part.PartitionCellByDatumPlane(cells=part.cells[:], datumPlane=part.datums[datum.id])
        except Exception:
            pass

    model.HomogeneousSolidSection(name="GirderSolidSection", material="GIRDER_CONCRETE", thickness=None)
    model.HomogeneousSolidSection(name="PierSolidSection", material="PIER_CONCRETE", thickness=None)
    part.SectionAssignment(region=regionToolset.Region(cells=part.cells[:]), sectionName="GirderSolidSection")
    for pier in plan["piers"]:
        pier_cells = part.cells.getByBoundingBox(
            xMin=pier["x"] - pier["width"] / 2.0,
            xMax=pier["x"] + pier["width"] / 2.0,
            yMin=-pier["height"],
            yMax=-pier["girder_depth"] * 0.90,
            zMin=-1.0e-6,
            zMax=plan["deck_width_m"] + 1.0e-6,
        )
        if len(pier_cells):
            part.SectionAssignment(region=regionToolset.Region(cells=pier_cells), sectionName="PierSolidSection")
        else:
            try:
                pier_cell = part.cells.findAt(((pier["x"], -0.5 * (pier["height"] + pier["girder_depth"]), plan["deck_width_m"] / 2.0),))
                part.SectionAssignment(region=regionToolset.Region(cells=pier_cell), sectionName="PierSolidSection")
            except Exception:
                pass

    elem_types = (
        ElemType(elemCode=C3D8R, elemLibrary=STANDARD),
        ElemType(elemCode=C3D6, elemLibrary=STANDARD),
        ElemType(elemCode=C3D4, elemLibrary=STANDARD),
    )
    try:
        part.setMeshControls(regions=part.cells[:], elemShape=HEX_DOMINATED, technique=SWEEP)
    except Exception:
        part.setMeshControls(regions=part.cells[:], elemShape=TET, technique=FREE)
    part.setElementType(regions=(part.cells[:],), elemTypes=elem_types)
    part.seedPart(size=plan["mesh_size_m"], deviationFactor=0.1, minSizeFactor=0.1)
    part.generateMesh()

    assembly = model.rootAssembly
    assembly.DatumCsysByDefault(CARTESIAN)
    instance = assembly.Instance(name="RigidFrameSolid-1", part=part, dependent=ON)
    assembly.Set(cells=instance.cells[:], name="RIGID_FRAME_SOLID")

    tol = plan["mesh_size_m"] * 0.65
    top_nodes = tuple(node for node in instance.nodes if abs(node.coordinates[1]) <= tol * 0.2)
    top_labels = tuple(node.label for node in top_nodes)
    assembly.Set(nodes=instance.nodes.sequenceFromLabels(top_labels), name="DECK_TOP_NODES")

    def set_nodes_by_box(name, x_min, x_max, y_min, y_max):
        nodes = tuple(
            node for node in instance.nodes
            if x_min - tol <= node.coordinates[0] <= x_max + tol
            and y_min - tol <= node.coordinates[1] <= y_max + tol
        )
        labels = tuple(node.label for node in nodes)
        assembly.Set(nodes=instance.nodes.sequenceFromLabels(labels), name=abaqus_name(name))

    support_depth = max(plan["mesh_size_m"], 1.0)
    set_nodes_by_box("ABUTMENT_LEFT", -tol, tol, -plan["end_depth_m"] - tol, 0.0)
    set_nodes_by_box("ABUTMENT_RIGHT", plan["total_length_m"] - tol, plan["total_length_m"] + tol, -plan["end_depth_m"] - tol, 0.0)
    for index, pier in enumerate(plan["piers"], start=1):
        set_nodes_by_box("PIER%02d_BASE" % index, pier["x"] - pier["width"] / 2.0, pier["x"] + pier["width"] / 2.0, -pier["height"] - support_depth, -pier["height"] + support_depth)
        set_nodes_by_box("PIER%02d_TOP" % index, pier["x"] - pier["width"] / 2.0, pier["x"] + pier["width"] / 2.0, -pier["girder_depth"] - support_depth, -pier["girder_depth"] + support_depth)

    for tendon in plan["tendon_groups"]:
        tendon_sketch = model.ConstrainedSketch(name=abaqus_name(tendon["name"] + "_sketch"), sheetSize=max(100.0, plan["total_length_m"] * 1.2))
        x0 = tendon["start_x_m"]
        x1 = tendon["end_x_m"]
        xm = 0.5 * (x0 + x1)
        y = tendon["path_y_m"]
        tendon_sketch.Spline(points=((x0, y), (xm, y * 1.10), (x1, y)))
        tendon_part = model.Part(name=abaqus_name(tendon["name"]), dimensionality=THREE_D, type=DEFORMABLE_BODY)
        tendon_part.BaseWire(sketch=tendon_sketch)
        del model.sketches[abaqus_name(tendon["name"] + "_sketch")]
        model.TrussSection(name=abaqus_name(tendon["name"] + "_Section"), material="PRESTRESS_STEEL", area=tendon["area_each_m2"] * tendon["count"])
        tendon_part.SectionAssignment(region=regionToolset.Region(edges=tendon_part.edges[:]), sectionName=abaqus_name(tendon["name"] + "_Section"))
        tendon_part.setElementType(regions=(tendon_part.edges[:],), elemTypes=(ElemType(elemCode=T3D2, elemLibrary=STANDARD),))
        tendon_part.seedPart(size=max(plan["mesh_size_m"] * 2.0, 2.0), deviationFactor=0.1, minSizeFactor=0.1)
        tendon_part.generateMesh()
        tendon_instance_name = abaqus_name(tendon["name"] + "-1")
        tendon_instance = assembly.Instance(name=tendon_instance_name, part=tendon_part, dependent=ON)
        assembly.translate(instanceList=(tendon_instance_name,), vector=(0.0, 0.0, plan["deck_width_m"] / 2.0))
        assembly.Set(nodes=tendon_instance.nodes[:], name=abaqus_name(tendon["name"] + "_PATH_NODES"))
        assembly.Set(edges=tendon_instance.edges[:], name=abaqus_name(tendon["name"] + "_EMBEDDED_EDGES"))

    host_region = regionToolset.Region(cells=instance.cells[:])
    for tendon in plan["tendon_groups"]:
        embedded_region = regionToolset.Region(edges=assembly.sets[abaqus_name(tendon["name"] + "_EMBEDDED_EDGES")].edges)
        model.EmbeddedRegion(
            name=abaqus_name("Embed_" + tendon["name"]),
            embeddedRegion=embedded_region,
            hostRegion=host_region,
            weightFactorTolerance=1.0e-6,
            absoluteTolerance=0.0,
            fractionalTolerance=0.05,
            toleranceMethod=BOTH,
        )

    model.StaticStep(name="ServiceLoad", previous="Initial", initialInc=0.1, maxInc=0.2, nlgeom=OFF)
    model.DisplacementBC(name="BC_ABUTMENT_LEFT", createStepName="Initial", region=assembly.sets["ABUTMENT_LEFT"], u1=0.0, u2=0.0, u3=0.0)
    model.DisplacementBC(name="BC_ABUTMENT_RIGHT", createStepName="Initial", region=assembly.sets["ABUTMENT_RIGHT"], u1=UNSET, u2=0.0, u3=0.0)
    for index in range(1, 3):
        model.DisplacementBC(name="BC_PIER%02d_BASE" % index, createStepName="Initial", region=assembly.sets["PIER%02d_BASE" % index], u1=0.0, u2=0.0, u3=0.0)
    model.Gravity(name="Load-G", createStepName="ServiceLoad", comp2=-9.81, distributionType=UNIFORM, field="")
    road_force = -plan["road_line_load_n_m"] * plan["total_length_m"] / max(len(top_nodes), 1)
    prestress_force = plan["prestress_balancing_load_n_m"] * plan["total_length_m"] / max(len(top_nodes), 1)
    model.ConcentratedForce(name="Load-road-equivalent", createStepName="ServiceLoad", region=assembly.sets["DECK_TOP_NODES"], cf2=road_force)
    model.ConcentratedForce(name="Load-prestress-equivalent", createStepName="ServiceLoad", region=assembly.sets["DECK_TOP_NODES"], cf2=prestress_force)

    model.FieldOutputRequest(name="F-Output-RigidFrameSolid", createStepName="ServiceLoad", variables=("S", "U", "RF"))
    model.HistoryOutputRequest(name="H-Output-PierBase", createStepName="ServiceLoad", variables=("RF1", "RF2", "RF3"), region=assembly.sets["PIER01_BASE"])

    job = mdb.Job(name=project, model=model_name, description="Generated V3 solid rigid-frame bridge", type=ANALYSIS, memory=90, memoryUnits=PERCENTAGE, echoPrint=OFF, modelPrint=OFF, contactPrint=OFF, historyPrint=OFF)
    job.writeInput(consistencyChecking=OFF)
    mdb.saveAs(pathName=project + ".cae")
    print("Generated V3 solid rigid-frame model: " + project + ".cae and " + project + ".inp")


if __name__ == "__main__":
    build_model()
'''

    def _build_plan(self, task: RigidFrameInput, design: RigidFrameDesign) -> dict[str, Any]:
        stations = self._stations(task)
        pier_width = max(4.0, task.deck_width_m * 0.32)
        outline = self._outline(task, design, stations, pier_width)
        road_line_load = (task.roadway_load_pa + task.human_load_pa + task.second_dead_load_pa) * task.deck_width_m
        prestress_force = sum(group.total_force_n for group in design.tendon_groups)
        prestress_balancing = min(0.45 * road_line_load, prestress_force / max(task.total_length_m, 1.0) * 0.015)
        return {
            "project_name": task.project_name,
            "analysis_type": "static",
            "spans_m": task.spans_m,
            "total_length_m": task.total_length_m,
            "deck_width_m": task.deck_width_m,
            "outline_xy": outline,
            "partition_stations_m": stations[1:-1],
            "piers": [
                {
                    "name": "pier01",
                    "x": task.pier_stations_m[0],
                    "height": task.resolved_pier_height_m,
                    "width": pier_width,
                    "girder_depth": height_at_station(task, design.section, task.pier_stations_m[0]),
                },
                {
                    "name": "pier02",
                    "x": task.pier_stations_m[1],
                    "height": task.resolved_pier_height_m,
                    "width": pier_width,
                    "girder_depth": height_at_station(task, design.section, task.pier_stations_m[1]),
                },
            ],
            "end_depth_m": height_at_station(task, design.section, 0.0),
            "mesh_size_m": max(min(task.main_span_m / 48.0, 4.0), 1.5),
            "materials": task.materials.__dict__,
            "tendon_groups": [self._tendon_plan(task, design, group) for group in design.tendon_groups],
            "road_line_load_n_m": road_line_load,
            "prestress_balancing_load_n_m": prestress_balancing,
            "response": design.response.__dict__ if design.response else None,
        }

    def _outline(self, task: RigidFrameInput, design: RigidFrameDesign, stations: list[float], pier_width: float) -> list[list[float]]:
        points: list[list[float]] = [[0.0, 0.0], [task.total_length_m, 0.0]]
        right_depth = height_at_station(task, design.section, task.total_length_m)
        points.append([task.total_length_m, -right_depth])
        piers = sorted(task.pier_stations_m, reverse=True)
        current_x = task.total_length_m
        for pier_x in piers:
            x_right = min(current_x, pier_x + pier_width / 2.0)
            x_left = max(0.0, pier_x - pier_width / 2.0)
            for x in sorted([station for station in stations if x_right < station < current_x], reverse=True):
                points.append([x, -height_at_station(task, design.section, x)])
            points.append([x_right, -height_at_station(task, design.section, x_right)])
            points.append([x_right, -task.resolved_pier_height_m])
            points.append([x_left, -task.resolved_pier_height_m])
            points.append([x_left, -height_at_station(task, design.section, x_left)])
            current_x = x_left
        for x in sorted([station for station in stations if 0.0 < station < current_x], reverse=True):
            points.append([x, -height_at_station(task, design.section, x)])
        points.append([0.0, -height_at_station(task, design.section, 0.0)])
        points.append([0.0, 0.0])
        return points

    def _tendon_plan(self, task: RigidFrameInput, design: RigidFrameDesign, group: Any) -> dict[str, Any]:
        mid_x = 0.5 * (group.start_x_m + group.end_x_m)
        local_depth = height_at_station(task, design.section, mid_x)
        if group.eccentricity_m >= 0:
            path_y = -max(0.35, 0.18 * local_depth)
        else:
            path_y = -max(0.50, 0.82 * local_depth)
        data = group.__dict__.copy()
        data["path_y_m"] = path_y
        return data

    def _stations(self, task: RigidFrameInput) -> list[float]:
        stations = {0.0, task.total_length_m, *task.pier_stations_m}
        span_start = 0.0
        for span in task.spans_m:
            for index in range(1, 7):
                stations.add(round(span_start + span * index / 6.0, 6))
            span_start += span
        for pier in task.pier_stations_m:
            stations.add(round(pier - max(2.0, task.deck_width_m * 0.16), 6))
            stations.add(round(pier + max(2.0, task.deck_width_m * 0.16), 6))
        return sorted(station for station in stations if 0.0 <= station <= task.total_length_m)
