"""Generate a reviewable Abaqus/CAE Python script from a multi-agent model plan."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

LOGGER = logging.getLogger(__name__)


class AbaqusCaeScriptBuilder:
    """Write an Abaqus Python script that creates a beam bridge model and input file."""

    def write(self, model_plan: dict[str, Any], workdir: Path) -> Path:
        workdir.mkdir(parents=True, exist_ok=True)
        project_name = model_plan["project_name"]
        script_path = workdir / f"{project_name}_build_model.py"
        script_path.write_text(self.render(model_plan), encoding="utf-8")
        LOGGER.info("Wrote Abaqus CAE build script: %s", script_path)
        return script_path

    def render(self, model_plan: dict[str, Any]) -> str:
        plan_json = json.dumps(model_plan, indent=2)
        return f'''# -*- coding: mbcs -*-
"""Generated by Bridge FEM Agent V2 multi-agent workflow.

Run with:
    abaqus cae noGUI={model_plan["project_name"]}_build_model.py

The script creates a reviewable Abaqus/CAE beam model, writes an input file,
and saves a .cae database in the current working directory.
"""

from __future__ import print_function

import json
import sys
from abaqus import *
from abaqusConstants import *
from caeModules import *
from driverUtils import executeOnCaeStartup
from mesh import ElemType
import regionToolset


MODEL_PLAN = r"""{plan_json}"""


def abaqus_value(value):
    return UNSET if value is None else value


def abaqus_name(value):
    if sys.version_info[0] < 3:
        try:
            if isinstance(value, unicode):
                return value.encode("mbcs")
        except NameError:
            pass
    return str(value)


def build_model():
    executeOnCaeStartup()
    plan = json.loads(MODEL_PLAN)
    project = abaqus_name(plan["project_name"])
    model_name = "BridgeSemanticModel"

    Mdb()
    try:
        del mdb.models["Model-1"]
    except Exception:
        pass
    model = mdb.Model(name=model_name)

    geometry = plan["geometry"]
    mesh_plan = plan["mesh"]
    section_plan = plan["section"]
    material_plan = plan["materials"]
    supports = plan["supports"]
    loads = plan["loads"]

    sketch = model.ConstrainedSketch(name="girder_axis_sketch", sheetSize=max(10.0, geometry["total_length_m"] * 1.2))
    points = geometry["girder_axis"]
    for start, end in zip(points[:-1], points[1:]):
        sketch.Line(point1=(start[0], start[2]), point2=(end[0], end[2]))
    part = model.Part(name="MainGirder", dimensionality=THREE_D, type=DEFORMABLE_BODY)
    part.BaseWire(sketch=sketch)
    del model.sketches["girder_axis_sketch"]

    material_key = material_plan["primary_material"]
    material_name = abaqus_name(material_key)
    material = material_plan["materials"][material_key]
    model.Material(name=material_name)
    model.materials[material_name].Density(table=((material["density_kg_m3"],),))
    model.materials[material_name].Elastic(table=((material["elastic_modulus_pa"], material["poisson_ratio"]),))

    section_name = abaqus_name(section_plan["name"])
    profile_name = abaqus_name(section_plan["name"] + "_Profile")
    model.RectangularProfile(name=profile_name, a=section_plan["width_m"], b=section_plan["height_m"])
    model.BeamSection(
        name=section_name,
        integration=DURING_ANALYSIS,
        poissonRatio=material["poisson_ratio"],
        profile=profile_name,
        material=material_name,
        temperatureVar=LINEAR,
        consistentMassMatrix=False,
    )
    edge_region = regionToolset.Region(edges=part.edges[:])
    part.SectionAssignment(region=edge_region, sectionName=section_name, offset=0.0, offsetType=MIDDLE_SURFACE, offsetField="", thicknessAssignment=FROM_SECTION)
    part.assignBeamSectionOrientation(region=edge_region, method=N1_COSINES, n1=(0.0, 0.0, -1.0))

    elem_code = B31
    if mesh_plan["element_type"].upper() == "B32":
        elem_code = B32
    part.setElementType(regions=(part.edges[:],), elemTypes=(ElemType(elemCode=elem_code, elemLibrary=STANDARD),))
    part.seedPart(size=mesh_plan["target_size_m"], deviationFactor=mesh_plan["deviation_factor"], minSizeFactor=mesh_plan["min_size_factor"])
    part.generateMesh()

    assembly = model.rootAssembly
    assembly.DatumCsysByDefault(CARTESIAN)
    instance = assembly.Instance(name="MainGirder-1", part=part, dependent=ON)

    all_edges_region = regionToolset.Region(edges=instance.edges[:])
    assembly.Set(edges=instance.edges[:], name="MAIN_GIRDER")

    for support in supports:
        vertex = instance.vertices.findAt(((support["x_m"], 0.0, 0.0),))
        assembly.Set(vertices=vertex, name=abaqus_name(support["name"]))

    if plan["analysis_type"] == "frequency":
        model.FrequencyStep(name="FrequencyStep", previous="Initial", numEigen=10)
        active_step = "FrequencyStep"
    else:
        model.StaticStep(name="LoadStep", previous="Initial", initialInc=0.1, maxInc=0.2, nlgeom=OFF)
        active_step = "LoadStep"

    for support in supports:
        dofs = support["dofs"]
        support_name = abaqus_name(support["name"])
        model.DisplacementBC(
            name=abaqus_name("BC_" + support["name"]),
            createStepName="Initial",
            region=assembly.sets[support_name],
            u1=abaqus_value(dofs.get("u1")),
            u2=abaqus_value(dofs.get("u2")),
            u3=abaqus_value(dofs.get("u3")),
            ur1=abaqus_value(dofs.get("ur1")),
            ur2=abaqus_value(dofs.get("ur2")),
            ur3=abaqus_value(dofs.get("ur3")),
            amplitude=UNSET,
            distributionType=UNIFORM,
            fieldName="",
            localCsys=None,
        )

    for load in loads:
        if load["type"] == "gravity":
            model.Gravity(name=abaqus_name(load["name"]), createStepName=active_step, comp3=load["components"]["comp3"], distributionType=UNIFORM, field="")
        elif load["type"] == "beam_line_load":
            model.LineLoad(name=abaqus_name(load["name"]), createStepName=active_step, region=all_edges_region, comp3=load["value"], distributionType=UNIFORM, field="")
        elif load["type"] == "concentrated_force":
            target_set = abaqus_name(supports[-1]["name"])
            kwargs = {{}}
            direction = load.get("direction", "z").lower()
            if direction == "x":
                kwargs["cf1"] = load["value"]
            elif direction == "y":
                kwargs["cf2"] = load["value"]
            else:
                kwargs["cf3"] = load["value"]
            model.ConcentratedForce(name=abaqus_name(load["name"]), createStepName=active_step, region=assembly.sets[target_set], **kwargs)

    model.FieldOutputRequest(name="F-Output-Bridge", createStepName=active_step, variables=("S", "U", "RF"))
    model.HistoryOutputRequest(name="H-Output-Reactions", createStepName=active_step, variables=("RF1", "RF2", "RF3"), region=assembly.sets[abaqus_name(supports[0]["name"])])

    job = mdb.Job(
        name=project,
        model=model_name,
        description="Generated by Bridge FEM Agent V2",
        type=ANALYSIS,
        memory=90,
        memoryUnits=PERCENTAGE,
        explicitPrecision=SINGLE,
        nodalOutputPrecision=SINGLE,
        echoPrint=OFF,
        modelPrint=OFF,
        contactPrint=OFF,
        historyPrint=OFF,
    )
    job.writeInput(consistencyChecking=OFF)
    mdb.saveAs(pathName=project + ".cae")
    print("Generated " + project + ".cae and " + project + ".inp")


if __name__ == "__main__":
    build_model()
'''
